server:
    port: 8081

# http://localhost:8081/swagger-ui/index.html#/
spring:
    application:
        name: "n3_seguranca_backend"

    datasource:
        driverClassName: "org.h2.Driver"
        username: "sa"
        password: ""
        # url: "jdbc:h2:file:./Users/diegoplaninscheck/n3_db"
        # url: jdbc:h2:file:C:/Users/diego/Documents/pac_db
        url: jdbc:h2:file:C:\Dev\Android\AppGoogle\forca_vendas_pac_backend/pac_db
        # jdbc:h2:file:C:/Users/diego/Documentos
        # /Users/diegoplaninscheck

    jpa:
        database-platform: "org.hibernate.dialect.H2Dialect"
        show-sql: true
        hibernate:
            ddl-auto: "update"

    h2:
        console:
            enabled: true
            path: "/h2-console"


    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://localhost:8080/realms/master"
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
